{% set name = "django-appointment" %}
{% set version = "3.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_appointment-{{ version }}.tar.gz
  sha256: f9763ade7e0c2fc8284dc15946574428de575c648150d44824388c2aa6dd4f1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2,<6.0
    - pillow ~=10.4
    - phonenumbers ~=8.13
    - django-phonenumber-field ~=8.0.0
    - babel ~=2.15
    - colorama ~=0.4
    - icalendar ~=6.3.1

test:
  imports:
    - appointment
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamspd/django-appointment
  summary: Managing appointment scheduling with customizable slots, staff features, and conflict handling.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
