{% set name = "django-appointment" %}
{% set version = "3.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_appointment-{{ version }}.tar.gz
  sha256: 674c97c8adfae5a9cfae423d4f315ae0cf7f8df197ff03dbb821866264b72fc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2
    - pillow ==10.4.0
    - phonenumbers ==8.13.42
    - django-phonenumber-field ==8.0.0
    - babel ==2.15.0
    - colorama >=0.4.6,<0.5.dev0

test:
  imports:
    - appointment
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamspd/django-appointment
  summary: Managing appointment scheduling with customizable slots, staff features, and conflict handling.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
